name: Deploy to One.com Sandbox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fast Native SFTP Deploy
        uses: Nandisha/sftp-deploy@v1.3.0
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 22
          local_path: ./
          remote_path: /webroots/62bd938a