name: Deploy to One.com Sandbox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Ultra Fast Native Sync via rsync
        run: |
          sshpass -p "${{ secrets.SFTP_PASSWORD }}" rsync -avz -e "ssh -p 22 -o StrictHostKeyChecking=no" \
            --exclude='.git*' \
            --exclude='.github*' \
            ./ ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}:/webroots/62bd938a
