name: Deploy to One.com Sandbox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Beschleuniger: Cache für Docker-Layer aktivieren
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: SFTP Deploy to Subdomain
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 22
          local_path: ./
          remote_path: /webroots/62bd938a